services:
  - type: web
    name: monopoly-websocket
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server_ws.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
